info.app:
  name: HMPPS Community Support Api
  version: 1.0

spring:
  application:
    name: hmpps-community-support-api

  flyway:
    locations: classpath:db/migration,classpath:db/seed

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${services.hmpps-auth-api.base-url}/.well-known/jwks.json
      client:
        registration:
          community-support-api-client:
            provider: hmpps-auth
            client-id: hmpps-community-support-api-2
            client-secret: clientsecret
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${services.hmpps-auth-api.base-url}/oauth/token
  http:
    codecs:
      max-in-memory-size: 10MB
  web:
    error:
      include-message: always

springdoc:
  swagger-ui:
    version: 5.32.11

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms
webclient:
  connect-timeout-seconds: 20
  read-timeout-seconds: 10
  write-timeout-seconds: 10
  manage-users-api:
    max-retry-attempts: 2

# Materialized view refresh configuration
case-list-view:
  refresh-rate-ms: 300000  # 5 minutes
services:
  hmpps-auth-api:
    base-url: ${HMPPS_AUTH_API_BASE_URL}
  core-person-record-api:
    base-url: ${CORE_PERSON_RECORD_API_BASE_URL}
  manage-users-api:
    base-url: ${MANAGE_USERS_API_BASE_URL}
    locations:
      auth-user-groups: "/externalusers/{userId}/groups"
      auth-user-details: "/users/{userName}"
  assess-risks-and-needs-api:
    base-url: ${ASSESS_RISKS_AND_NEEDS_API_BASE_URL}
  nDelius-api:
    base-url: ${NDELIUS_API_BASE_URL}
  prison-api:
    base-url: ${PRISON_API_BASE_URL}

reference-data:
  probation-offices:
    path: "reference-data/probation-offices-v0.csv"