services:
  hmpps-auth-api:
    base-url: "http://hmpps-auth:8090/auth"
  core-person-record-api:
    base-url: ${CORE_PERSON_RECORD_API_BASE_URL}
  manage-users-api:
    base-url: ${MANAGE_USERS_API_BASE_URL}
    locations:
      auth-user-groups: "/externalusers/{userId}/groups"
      auth-user-details: "/users/{userName}"
  nDelius-api:
    base-url: ${NDELIUS_API_BASE_URL}
  prison-api:
    base-url: ${PRISON_API_BASE_URL}
