spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin_password
  flyway:
    locations: classpath:db/migration,classpath:db/seed,classpath:db/local
    clean-disabled: false
  security:
    oauth2:
      client:
        registration:
          community-support-api-client:
            client-id: hmpps-community-support-ipb-ui-client-1
            client-secret: clientsecret

services:
  hmpps-auth-api:
    base-url: http://hmpps-auth:8090/auth
  core-person-record-api:
    base-url: http://localhost:9091
  manage-users-api:
    base-url: http://localhost:9091/manage-users
    locations:
      auth-user-groups: "/externalusers/{userId}/groups"
      auth-user-details: "/users/{userName}"
  assess-risks-and-needs-api:
    base-url: http://localhost:9091/assess-risks-and-needs
  nDelius-api:
    base-url: http://localhost:9091
  prison-api:
    base-url: http://localhost:9091/prison-api

notify:
  api.key: "${NOTIFY_API_KEY:invalid-key}"

logging:
  level:
    uk.gov.justice.digital.hmpps.communitysupportapi.client: DEBUG
